name: 'Upload Artifact'
description: 'Package and upload an artiofact to the workflow storage'
inputs:
    artifact_name:
        required: true
        type: string
    executable_path:
        required: true
        type: string
    vcpkg_triplet:
        required: true
        type: string
outputs:
    artifact_name: 
        description: 'Echo of the input'  
        value: ${{inputs.artifact_name}}
runs:
    using: "composite"
    steps:
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: ${{inputs.artifact_name}}
            path: |
                ${{inputs.executable_path}}
                ./build/vcpkg_installed/${{inputs.vcpkg_triplet}}/share/*/copyright
                ./base/*
                ./BFA_Assets/*
                ./base_new/*
                ./COPYING.txt
                ./alsoft.ini
                ./README.md
