name: 'Package Formatter'
description: 'Format workflow artifact to release packages'
inputs:
    artifact_name:
        required: true
        type: string
    upload_url:
        required: true
        type: string
    commands:
        required: true
        type: string
    access_token:
        required: true
        type: string
    second_token:
        required: true
        type: string
    run-id:
        required: true
        type: string
outputs:
    artifact_name: 
        description: 'Echo of the input'  
        value: ${{inputs.artifact_name}}

runs:
  using: "composite"
  steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{inputs.artifact_name}}
          github-token: ${{ inputs.second_token }}
          path: ${{github.workspace}}/temp
          run-id: ${{ inputs.run-id }}
      - name: Zip artifact files
        shell: bash
        working-directory: ${{github.workspace}}/temp
        run: |
          [ -d ./BFA_Assets ] && cp -r -u  -f ./BFA_Assets/* .
          [ -d ./BFA_Assets ] && rm -r ./BFA_Assets
          [ -d ./BFA_Assets_classic ] && cp -r -u  -f ./BFA_Assets_classic/* .
          [ -d ./BFA_Assets_classic ] && rm -r ./BFA_Assets_classic
          rm -r ./base/renderprogs
          mkdir third-party-licenses
          ${{inputs.commands}}
          rm -d -R build
          zip -m -r ${{inputs.artifact_name}}.zip .
      - name: Upload Artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ inputs.access_token }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ${{github.workspace}}/temp/${{inputs.artifact_name}}.zip
          asset_name: ${{inputs.artifact_name}}.zip
          asset_content_type: application/zip
      - name: Delete artifact zip file
        working-directory: ${{github.workspace}}/temp
        shell: bash
        run: rm ${{inputs.artifact_name}}.zip