/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.3.1-26-gca55240b8c"
#endif /* AVUTIL_FFVERSION_H */
