/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.0.1-3-gb655beb025-20220425"
#endif /* AVUTIL_FFVERSION_H */
