name: Build Linux

on:
    workflow_call:
        inputs:
            build_type:
                required: true
                type: string
            version:
                required: true
                type: string


jobs:
    linux-build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v5
          id: step1
          with:
            submodules: recursive
            ref: ${{ github.event.pull_request.head.sha }}
    
        # - name: Patch OpenAL-Soft
        #   id: step1f
        #   run: |
        #     cd vcpkg
        #     git apply ../.github/tools/openal-fix.patch
            
        - uses: actions/checkout@v5
          id: step2
          with:
            repository: MadDeCoDeR/BFA-Assets
            path: BFA_Assets

        - uses: actions/checkout@v5
          id: step21
          with:
            repository: MadDeCoDeR/BFA-Assets
            ref: classic
            path: BFA_Assets_classic
    
        - name: Download Depedencies
          id: step4
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential autoconf libtool cmake libglu1-mesa-dev freeglut3-dev mesa-common-dev libxmu-dev libxi-dev libgl-dev libx11-dev libxft-dev libxext-dev nasm libwayland-dev libxkbcommon-dev libegl1-mesa-dev libdecor-0-dev libxrandr-dev libxxf86vm-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev python3-jinja2 libltdl-dev
    
        - name: Cache linux vcpkg
          id: step5
          uses: actions/cache@v4
          with: 
              path: ${{github.workspace}}/build/vcpkg_installed
              key: ${{runner.os}}-vcpkg-${{hashfiles('neo/linux-status')}}
              restore-keys: |
                ${{ runner.OS }}-vcpkg-
    
    
        - name: Configure CMake
          id: step6
          env:
            CC: gcc-13
            CXX: g++-13
          working-directory: ${{github.workspace}}/neo
          run: cmake -B ${{github.workspace}}/build --preset=linux-${{inputs.build_type}}
    
        - name: Build
          id: step7
          env:
            CC: gcc-13
            CXX: g++-13
          run: cmake --build ${{github.workspace}}/build --parallel=16 --target DoomBFA
          
        - name: Archive production artifacts
          id: step8
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: linux-${{inputs.version}}-${{inputs.build_type}}
            executable_path: ./build/DoomBFA
            vcpkg_triplet: x64-linux
            additional_paths: |
                            ./build/_deps/openxr-build/src/loader/*.so*
                            ./build/_deps/openxr-build/src/loader/*.so
                            ./BFA_Assets/*
    
        - name: Archive Classic Edition production artifacts
          id: step81
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: linux-${{inputs.version}}-${{inputs.build_type}}-classic
            executable_path: ./build/DoomBFA
            vcpkg_triplet: x64-linux
            additional_paths: |
                          ./build/_deps/openxr-build/src/loader/*.so*
                          ./build/_deps/openxr-build/src/loader/*.so
                          ./BFA_Assets_classic/*

        - name: Configure CMake Debug
          id: step9
          env:
            CC: gcc-13
            CXX: g++-13
          working-directory: ${{github.workspace}}/neo
          run: cmake -B ${{github.workspace}}/build --preset=linux-relwithdebuginfo
    
        - name: Build Debug
          id: step10
          env:
            CC: gcc-13
            CXX: g++-13
          # Build your program with the given configuration
          run: cmake --build ${{github.workspace}}/build --parallel=16 --target DoomBFA
          
        - name: Archive debug artifacts
          id: step11
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: linux-${{inputs.version}}-debug
            executable_path: ./build/DoomBFA
            vcpkg_triplet: x64-linux
            additional_paths: |
                            ./build/_deps/openxr-build/src/loader/*.so*
                            ./build/_deps/openxr-build/src/loader/*.so
                            ./BFA_Assets/*

        - name: Save logs - VCPKG
          if: ${{ failure() }}
          uses: actions/upload-artifact@v4
          with:
              name: vcpkg-linux-logs
              path: ${{github.workspace}}/vcpkg/buildtrees/*/*.log