name: Build x64 Windows

on:
    workflow_call:
        inputs:
            build_type:
                required: true
                type: string
            version:
                required: true
                type: string

jobs:
    windows-build:
        runs-on: windows-latest
    
        steps:
        - uses: actions/checkout@v5
          with:
            submodules: recursive
            ref: ${{ github.event.pull_request.head.sha }}
        
        - name: Patch OpenAL-Soft
          id: step1f
          run: |
            cd vcpkg
            git apply ../.github/tools/openal-fix.patch

        - uses: actions/checkout@v5
          with:
            repository: MadDeCoDeR/BFA-Assets
            path: BFA_Assets

        - uses: actions/checkout@v5
          with:
            repository: MadDeCoDeR/BFA-Assets
            ref: classic
            path: BFA_Assets_classic
    
        - name: setup-msbuild
          uses: microsoft/setup-msbuild@v2
          with:
            vs-version: '[17.0, 18.0)'
            msbuild-architecture: x64
    
        - name: Cache Windows vcpkg
          uses: actions/cache@v4
          with: 
              path: ${{github.workspace}}/build/vcpkg_installed
              key: ${{runner.os}}-vcpkg-${{hashfiles('neo/windows-status')}}
              restore-keys: |
                ${{ runner.OS }}-vcpkg-
              enableCrossOsArchive: true
    
        - name: Configure CMake
          working-directory: ${{github.workspace}}/neo
          shell: powershell
          run: cmake -B ${{github.workspace}}/build --preset=windows-x64-2022
          
        - name: Build
          # Build your program with the given configuration
          #run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
          run: MSBuild ${{github.workspace}}/build/DoomBFA.vcxproj -property:Configuration=${{inputs.build_type}}
    
        - name: BuildDebug
          #run: cmake --build ${{github.workspace}}/build --config retwithdebugsymbols
          run: MSBuild ${{github.workspace}}/build/DoomBFA.vcxproj -property:Configuration=retwithdebugsymbols
          
        - name: Archive production artifacts
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: windows-${{inputs.version}}-${{inputs.build_type}}-x64
            executable_path: ./build/${{inputs.build_type}}/DoomBFA.exe
            vcpkg_triplet: x64-windows-static-md
            additional_paths: |
                            ./BFA_Assets/*

        - name: Archive Classic Edition production artifacts
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: windows-${{inputs.version}}-${{inputs.build_type}}-x64-classic
            executable_path: ./build/${{inputs.build_type}}/DoomBFA.exe
            vcpkg_triplet: x64-windows-static-md
            additional_paths: |
                          ./BFA_Assets_classic/*
        
        - name: Archive debug artifacts
          uses: ./.github/actions/upload_artifact
          with:
            artifact_name: windows-${{inputs.version}}-debug-x64
            executable_path: ./build/retwithdebugsymbols/DoomBFA.*
            vcpkg_triplet: x64-windows-static-md
            additional_paths: |
                            ./BFA_Assets/*

        - name: Save logs - VCPKG
          if: ${{ failure() }}
          uses: actions/upload-artifact@v4
          with:
              name: vcpkg-windows-64-logs
              path: ${{github.workspace}}/vcpkg/buildtrees/*/*.log